var num = 25;
var str = "Hello, TypeScript!";
var bool = true;
var nullValue = null;
var undefinedValue = undefined;
var anyValue = "Can be anything";
console.log("Number:", num);
console.log("String:", str);
console.log("Boolean:", bool);
console.log("Null:", nullValue);
console.log("Undefined:", undefinedValue);
console.log("Any:", anyValue);
